server:
   port: 31860
qiniu:
  accessKey: eeYtcWvGPXqjEiTIxDljeVu8qxFpwdXOvGo4PURq
  secretKey: LHkSG-HRLccuUYSgb-TX0ZcDrsyUMEzSg6Z3GG6G
  publicBucket: hfc-lucifer
  url: http://ojvbqldpg.bkt.clouddn.com/
multipart:
  maxFileSize: 10Mb
  maxRequestSize: 30Mb